[workspace]
authors = ["Yuekai Sun <yuekai@gmail.com>"]
channels = ["conda-forge"]
name = "little-coder"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
pip = ">=26.1.1,<27"
nodejs = ">=20.6"

[pypi-dependencies]
harbor = ">=0.6.4, <0.7"
